name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    name: Test failing spec detector
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Lint  files
        run: bundle exec rake rubocop
      - name: Run tests
        run: bundle exec rake spec
